---
- hosts: localhost
  gather_facts: false
  connection: local
  roles:
    - azure_keyvault_secret
  tasks:
    - name: Look up secret when ansible host is general VM
      vars:
        vault_name: 'rg-senugu-kv'
        secret_name: 'mytestsecret'
      debug: msg="the value of this secret is {{lookup('azure_keyvault_secret',secret_name,vault_name=vault_name)}}"

