---
- hosts: myhosts
  gather_facts: false
  roles:
    - azure_keyvault_secret
  tasks:
    - name: ping test
      action: ping
    - name: Look up secret when ansible host is general VM
      vars:
        vault_name: 'rg-senugu-kv'
        secret_name: 'adminUser'
      debug: msg="the value of this secret is {{lookup('azure_keyvault_secret',secret_name,vault_name=vault_name)}}"
      delegate_to: localhost

